lab4/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'labassignment4/',include('labassignment4.urls')),
]

labassignment4/urls.py
from django.urls import path
from labassignment4 import views

app_name = 'labassignment4'

urlpatterns = [
    path(r'', views.index, name='index'),
    path(r'about/', views.about, name='about'),
    path(r'<int:cat_no>/', views.detail, name='detail'),
    path(r'products/',views.products,name='products'),
    path(r'placeorder/',views.place_order,name='placeorder'),
    path(r'products/<int:prod_id>/', views.productdetail, name='productdetail'),
    path(r'login/', views.user_login, name='login'),
    path(r'logout/', views.user_logout, name='logout'),
    path(r'myorders/', views.myorders, name='myorders'),
    ]
    
    

labassignment4/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200)
    warehouse = models.CharField(max_length=200)
    
    def __str__(self):
        return self.name
        
    
class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products',on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField(default=100, validators=[MinValueValidator(0),MaxValueValidator(1000)])
    available = models.BooleanField(default=True)
    description = models.TextField(blank=True,default='')
    interested = models.PositiveIntegerField(default=0)
    
    def __str__(self):
        return self.name
        
    def refill(self):
        self.stock = self.stock+100
        return self.stock
    
class Client(User): 
    PROVINCE_CHOICES = [('AB', 'Alberta'), ('MB', 'Manitoba'), ('ON', 'Ontario'), ('QC', 'Quebec')]
    company = models.CharField(max_length=50, blank=True, default='')
    shipping_address = models.CharField(max_length=300, null=True, blank=True)
    city = models.CharField(max_length=20,default='Windsor')
    province=models.CharField(max_length=2, choices=PROVINCE_CHOICES, default='ON')
    interested_in = models.ManyToManyField(Category)
    
    def __str__(self):
        return self.username
    
class Order(models.Model):
    product = models.ForeignKey(Product,on_delete=models.PROTECT)
    client = models.ForeignKey(Client,on_delete=models.PROTECT)
    num_units = models.PositiveIntegerField()
    ORDER_CHOICES = [(0,'Order Cancelled'),(1,'Order Placed'),(2,'Order Shipped'),(3,'Order Delivered')]
    order_status = models.IntegerField(choices=ORDER_CHOICES, default=1)
    status_date = models.DateField(default=date.today)
    
    def __str__(self):
        return "For "+str(self.num_units)+" "+str(self.product)+"(s) by "+str(self.client)
    
    def total_cost(self):
        return self.num_units*self.product.price

labassignment4/forms.py
from django import forms
from labassignment4.models import Order,Client,Product
from django.core.validators import MinValueValidator


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['client','product','num_units']
    
    #client = forms.ModelChoiceField(widget=forms.RadioSelect,queryset=Client.objects.all(),to_field_name="username",label='Client name')
    #product = forms.ModelChoiceField(queryset=Product.objects.all().order_by('id'),to_field_name="name")
    #num_units = forms.IntegerField(label='Quantity')
    
class InterestForm(forms.Form):
    INT_CHOICES = [('Yes','Yes'),('No','No')]
    interested = forms.ChoiceField(widget=forms.RadioSelect,choices=INT_CHOICES)
    quantity = forms.IntegerField(initial=1,min_value=0)
    comments = forms.CharField(widget=forms.Textarea,label='Additional Comments',required=False)

labassignment4/views.py
from datetime import date, datetime

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.db.models import F
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from .forms import InterestForm, OrderForm
from .models import Category, Client, Order, Product

# Create your views here.

def index(request):
    cat_list = Category.objects.all().order_by('id')[:10]

    if 'last_login' in request.session :
        logininfo = request.session['last_login']
    else :
        logininfo = 'Your last login was more than an hour ago'
    return render(request, 'labassignment4/index.html', {'cat_list': cat_list,'logininfo':logininfo})
    
def about(request):
    if 'about_visits' in request.session:
        last_visit = request.session['about_visits']
        request.session['about_visits']=last_visit+1
        request.session.set_expiry(10)        
    else :
        request.session['about_visits']=1
        last_visit=0
        request.session.set_expiry(300)
    return render(request, 'labassignment4/about.html',{'last_visit':last_visit})
    
def detail(request,cat_no):
    #response = HttpResponse()
    cat_name = get_object_or_404(Category,pk=cat_no)
    catprods = Product.objects.filter(category=cat_no)
    return render(request, 'labassignment4/detail.html', {'cat_name': cat_name,'prod_list': catprods })
    
def products(request):
    prodlist = Product.objects.all().order_by('id')
    return render(request,'labassignment4/products.html',{'prodlist':prodlist})

def place_order(request):
    msg = ''
    prodlist = Product.objects.all()
    if request.method == 'POST' :
        form = OrderForm(request.POST,initial={'status_date':date.today(),'order_status':'Order Placed'})
        if form.is_valid():
            order = form.save(commit=False)
            if order.num_units <= order.product.stock :
                order.save()
                msg = 'Your order has been placed successfully'
            else:
                msg = 'We do not have sufficient sock to fill your order.'
            return render(request, 'labassignment4/order_response.html',{'msg':msg})
        
    else :
        form = OrderForm()
        return render(request, 'labassignment4/placeorder.html',{'form':form, 'msg':msg, 'prodlist':prodlist})
        
def productdetail(request, prod_id):
    prod = Product.objects.get(pk=prod_id)
    if request.method == 'POST':
        form = InterestForm(request.POST)
        if form.is_valid():
            if form.cleaned_data['interested'] == 'Yes' :
                prod.interested = prod.interested + 1
                print(prod.id)
                prod.save()
                return redirect('/labassignment4/')
            else :
                return redirect('/labassignment4/')
    else :
        form = InterestForm()
        return render(request, 'labassignment4/productdetail.html',{'form':form,'prod':prod})

def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username,password=password)
        if user :
            if user.is_active:
                if 'last_login' not in request.session :
                    request.session['last_login'] = str(datetime.now())
                    request.session.set_expiry(3600)
                login(request,user)
                return HttpResponseRedirect(reverse('labassignment4:index'))
            else:
                return HttpResponse('Your account is disabled')
        else :
            return HttpResponse('Invalid Login details')
    else :
        return render(request, 'labassignment4/login.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('labassignment4:index'))

def myorders(request):
    if request.user.is_authenticated :
        try :
            usobjid = Client.objects.get(pk=request.user.id)
            orderset = usobjid.order_set.all()
            #return HttpResponse(orderset)
        except: 
            return HttpResponse("This user name is not registered")
        
        return render(request, 'labassignment4/myorders.html',{'orderset':orderset})
    else :
        return HttpResponse("User not authenticated")

labassignment4/templates/labassignment4/about.html
{% extends 'labassignment4/base.html' %}
{% block body_block %}
    <h2>This is the about page</h2>
    {% if last_visit %}
    <h3>Total visits : {{ last_visit }} </h3>
    {% endif %}
    <p><a href={% url 'labassignment4:index' %}>Main page (namespaced URL)</a></p>
    <p><a href="/labassignment4/">Main page (hardcoded URL)</a></p>
{% endblock %}

labassignment4/templates/labassignment4/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}"/>
        <title>Online Store APP - {% block title %}Welcome!{% endblock %}</title>
    </head>
<body>
    <div>
        <h1>{% block myhdg %}
            {% if user.is_authenticated %}
            <p>Hi, {{ user.get_username }}</p>
            {% else %}
            <p>Hi User</p>
            {% endif %}
            {% endblock %}</h1>
            {% block body_block %}*** {% endblock %}
        </div>
        <hr/>
        <div>
            <ul>
                <li class="hbar1"><a href="/labassignment4/about/">Find out about this site</a></li>
                <li class="hbar1"><a href = "{% url 'labassignment4:index' %}">Click here to return to main page</a><br/></li>
                <li class="hbar1"><a href="{% url 'labassignment4:products' %}">Products</a></li>
            </ul>
        </div>
</body>
</html>

labassignment4/templates/labassignment4/detail.html
{% extends 'labassignment4/base.html' %}
{% block body_block %}
    {% if cat_name %}
        
        <h3>Category:  {{ cat_name.name }}</h3>
        <p>Warehouse location : {{ cat_name.warehouse }}</p
        {% if prod_list %}
        <ul>
            {% for prods in prod_list %}
            <li>{{ prods.name }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    {% endif %}
    <p><a href={% url 'labassignment4:index' %}>Main page (namespaced URL)</a></p>
{% endblock %}

labassignment4/templates/labassignment4/index.html
{% extends 'labassignment4/base.html' %}

{% block body_block %}
{% if cat_list %}
    <h2>List of Categories</h2>
    <ol>
        {% for cat in cat_list %}
            <li><a href="{% url 'labassignment4:detail' cat_no=cat.id %}"> {{ cat.name }} </a></li>
        {% endfor %}
    </ol>
    {% else %}
        <strong>There are no available categories!</strong>
    {% endif %}
    </div>
    <div>
        {% if logininfo %}
            <p>Last login : {{logininfo}}</p>
        {% endif %}</div>
        
        <div>    
{% endblock %}

labassignment4/templates/labassignment4/index0.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Online Store APP</title>
</head>
<body>
    {% if cat_list %}
    <h2>List of Categories</h2>
    <ol>
        {% for cat in cat_list %}
            <li><a href={% url 'labassignment4:detail' cat_no=cat.id %}> {{ cat.name}} </li>
        {% endfor %}
    </ol>
    {% else %}
        <strong>There are no available categories!</strong>
    {% endif %}
    <p><a href={% url 'labassignment4:about' %}>About page</p>
</body>
</html>

labassignment4/templates/labassignment4/login.html
<!DOCTYPE html>
<html>
    <title>
        Login
    </title>
</html>
<body>
    <h2>Login Page</h2>
    <form action="/labassignment4/login/" method="post">
        {% csrf_token %}
        <div>
            <label for="username">Username</label>
            <input type="text" name="username" id="username"/>
        </div>
        <div>
            <label for="password">Password</label>
            <input type="password" name="password" id="password"/>
        </div>
        <div>
            <input type="submit" value="submit">
        </div>
    </form>
</body>

labassignment4/templates/labassignment4/myorders.html
{% extends 'labassignment4/base.html' %}
{% block body_block %}
    {% if orderset %}
    <h4>Orders :</h4>
    <ul>
        {% for orders in orderset %}
        <li>
            {{ orders.client }} placed order for {{orders.num_units}} {{ orders.product }}(s)
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <h4>You have not placed any orders</h4>
    {% endif %}
{% endblock %}

labassignment4/templates/labassignment4/order_response.html
{% extends 'labassignment4/base.html' %}
{% block body_block %}
    {% if msg %}
    <h3>{{ msg }}</h3>
    {% endif %}
{% endblock %}

labassignment4/templates/labassignment4/placeorder.html
{% extends 'labassignment4/base.html' %}
{% block body_block %}
    {% if prodlist %}
        <h4> Products : </h4>
        <ul>
            {% for prods in prod_list %}
            <li>
                {{prods.name}}
            </li>
            {% endfor %}
        </ul>
    {% endif %}
    
    <form action="/labassignment4/placeorder/" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="submit">
        {% if msg %}
            <p>{{msg}}</p>
        {% endif %}
    </form>
{% endblock %}

labassignment4/templates/labassignment4/productdetail.html
{% extends 'labassignment4/base.html' %}
{% block body_block %}
        {% if prod.available %}
            <h3>{{ prod.name }}</h3>
            <h4>People interested : {{ prod.interested }}</h4>
            <h4>Price : {{ prod.price }}</h4>
        {% else %}
            <h3>Product {{ prod.name }} is not available</h3>
        {% endif %}
    <form action="{% url 'labassignment4:productdetail' prod.id %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="sumbit">
    </form>
{% endblock %}
    

labassignment4/templates/labassignment4/products.html
{% extends 'labassignment4/base.html' %}
{% block body_block %}
    {% if prodlist %}
        <h4> Products : </h4>
        <ul>
            {% for prods in prodlist %}
            <li>
                <p><a href={% url 'labassignment4:productdetail' prods.id %}>{{ prods.name}}</p>
            </li>
            {% endfor %}
        </ul>
    {% endif %}
    <p><a href="{% url 'labassignment4:placeorder' %}">Place order</a></li></p>
{% endblock %}